### ISSUE TITLE
Automate or remove mirror

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/rubygem-asciidoctor-deb#3]
@aerostitch @Mogztter Can you confirm this repository is only serving as a mirror? If so, we should either automate that mirror (so it stays updated) or just remove it. How do you think we should proceed?

I think GitLab supports mirroring a repository to another location. I'd be in support of that approach. Let me know if you need assistance getting that set up.

If we decide to keep the repository, we should shut down the issue tracker since this is not the primary repository.

**Comment by Mogztter** [comment]
> Can you confirm this repository is only serving as a mirror

Yes.

> If so, we should either automate that mirror (so it stays updated) or just remove it. How do you think we should proceed?
> I think GitLab supports mirroring a repository to another location. I'd be in support of that approach. Let me know if you need assistance getting that set up.

Last time I checked the "Mirror repository" wasn't available on GitLab but now it's 😄 
For reference, the source repository is: https://salsa.debian.org/ruby-team/asciidoctor

And the mirroring is enabled!

![mirror-ok](https://user-images.githubusercontent.com/333276/47492833-30a57a80-d84e-11e8-90d4-bb84a47f03e1.png)

> If we decide to keep the repository, we should shut down the issue tracker since this is not the primary repository.

I think we should keep the issue tracker as a discussion system. The whole idea is to lower the barrier to contribute to the Debian package. I think it's easier to report a bug on GitHub than to report a bug on Debian: https://www.debian.org/Bugs/Reporting

So if someone report a bug here it's actually a good thing because we can start the discussion and eventually open a bug in the Debian Bug tracking system.

**Comment by Mogztter** [comment]
By the way, thank @aerostitch for your continuous efforts on the asciidoctor package! 👏

**Comment by aerostitch** [comment]
Cool, thanks. I don't have the rights to do anything on this repo but I'll be watching the issues here.
Note that you can also create merge requests on Salsa too if the Debian BTS is too much of a burden. :wink: 
Thanks for checking!

**Comment by aerostitch** [comment]
Awesome, thanks @mojavelinux ! :)
I think we're good on this issue, so closing!

**Comment by mojavelinux** [comment]
Sounds good to me! @aerostitch I invited you as an admin on this repository so you can make any adjustments necessary. If you need anything else from me, just let me know.

**Comment by aerostitch** [comment]
I will, thanks a lot! :)
